alive. PING command
electric-sheep-co/arduino-redis pull request #78
Opened 2023-12-01 21:33 UTC by ip75

%SUBJ%

2023-12-01 23:38 UTC, rpj commented on Redis.cpp
> +bool Redis::alive()
```suggestion
bool Redis::ping()
```

Unless absolutely necessary we'd prefer to keep methods that invoke Redis commands named the same as the Redis command they invoke.

2023-12-01 23:39 UTC, rpj commented on Redis.h
> +  bool alive();
```suggestion
  bool ping();
```

2023-12-01 23:39 UTC, rpj commented on Redis.h
> +   * Send PING command to redis to check is it alive
```suggestion
   * Send PING command to redis to check if it is alive
```

2023-12-01 23:41 UTC, rpj requested changes
Hi @ip75,

Thank you so much for your contribution, and welcome to the project!

There are a couple changes - just to naming - that I'd like to see with the code, plus I'd ask you to [add a test](https://github.com/electric-sheep-co/arduino-redis/blob/master/CONTRIBUTING.md?plain=1#L35) for this added method to the test suite & make sure your code [passes](https://github.com/electric-sheep-co/arduino-redis/actions/runs/7065427255/job/19238188745?pr=78) all the current tests as well. If you have trouble getting the [test harness](https://github.com/electric-sheep-co/arduino-redis#test-harness) running on your local system, please reach out and I'd be happy to help.

Additionally, if you wouldn't mind adding a short description to this PR (currently it just says "%SUBJ%") I would appreciate it.

Thank you again!
-RPJ

2023-12-10 18:13 UTC, ip75 commented
Hello
I absolutely agree with you. I've changed comment for pull request.

2023-12-16 22:36 UTC, closed without merging